[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_FLAGS = "--shamefully-hoist"

[dev]
  command = "pnpm run dev"
  targetPort = 4321
  publish = "dist"


